"""aaaaaaa112

Revision ID: 6a1c2660cd26
Revises: c3c1e1fbf045
Create Date: 2019-05-04 20:18:37.829956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1c2660cd26'
down_revision = 'c3c1e1fbf045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobname', sa.String(length=32), nullable=True),
    sa.Column('wages', sa.String(length=32), nullable=True),
    sa.Column('worktime', sa.String(length=32), nullable=True),
    sa.Column('work_address', sa.String(length=128), nullable=True),
    sa.Column('job_company', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
