"""init database2

Revision ID: 707a98c4ad7d
Revises: aea8b8af1f4b
Create Date: 2019-05-05 22:44:51.794517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707a98c4ad7d'
down_revision = 'aea8b8af1f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_state', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_state')
    # ### end Alembic commands ###
