"""login time

Revision ID: 7ec443ec75ae
Revises: 915a0ff041dd
Create Date: 2019-05-10 22:47:09.525905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec443ec75ae'
down_revision = '915a0ff041dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logindated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'logindated_at')
    # ### end Alembic commands ###
