"""aaaaaaa1122

Revision ID: 8cd27a4d1078
Revises: 6a1c2660cd26
Create Date: 2019-05-05 00:32:37.785100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd27a4d1078'
down_revision = '6a1c2660cd26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('describe', sa.String(length=128), nullable=True))
    op.add_column('job', sa.Column('job_des', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_des')
    op.drop_column('job', 'describe')
    # ### end Alembic commands ###
