"""init database21212311

Revision ID: 9b7565731612
Revises: 707a98c4ad7d
Create Date: 2019-05-05 23:08:59.009709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7565731612'
down_revision = '707a98c4ad7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_state', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_state')
    # ### end Alembic commands ###
