"""tian

Revision ID: 9c53f8de8092
Revises: 4c15bffbb152
Create Date: 2019-05-01 17:49:02.829692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c53f8de8092'
down_revision = '4c15bffbb152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eusername', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=32), nullable=False),
    sa.Column('company_url', sa.String(length=32), nullable=False),
    sa.Column('logo', sa.String(length=150), nullable=False),
    sa.Column('company_des', sa.String(length=50), nullable=False),
    sa.Column('company_det', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company')
    # ### end Alembic commands ###
