"""init aaaaaaa

Revision ID: 9da59b111634
Revises: 9b7565731612
Create Date: 2019-05-06 13:06:04.140029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da59b111634'
down_revision = '9b7565731612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_state2', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_state2')
    # ### end Alembic commands ###
