"""aaaaaa

Revision ID: b4f627739bba
Revises: b316bd2d7f14
Create Date: 2019-05-02 18:03:43.435361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4f627739bba'
down_revision = 'b316bd2d7f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'address',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'company_des',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('company', 'company_det',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('company', 'company_url',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'email',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'eusername',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'logo',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('company', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'slug',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('message', 'email',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('message', 'jianli_url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('message', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('message', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('message', 'worktime',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('message', 'worktime',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('message', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('message', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('message', 'jianli_url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('message', 'email',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'slug',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'logo',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('company', 'eusername',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'email',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'company_url',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'company_det',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('company', 'company_des',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('company', 'address',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
