"""aaaaaaa11

Revision ID: e80aa02d84aa
Revises: b4f627739bba
Create Date: 2019-05-04 20:08:57.298959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80aa02d84aa'
down_revision = 'b4f627739bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobname', sa.String(length=32), nullable=True),
    sa.Column('wages', sa.String(length=32), nullable=True),
    sa.Column('worktime', sa.String(length=32), nullable=True),
    sa.Column('work_address', sa.String(length=128), nullable=True),
    sa.Column('job_company', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
